# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.zoomIndicator = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.zoomIndicator.setDecimals(1)
        self.zoomIndicator.setMinimum(0.0)
        self.zoomIndicator.setMaximum(100.0)
        self.zoomIndicator.setSingleStep(0.1)
        self.zoomIndicator.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.zoomIndicator.setProperty("value", 1.0)
        self.zoomIndicator.setObjectName("zoomIndicator")
        self.horizontalLayout_2.addWidget(self.zoomIndicator)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pageIndicator = QtWidgets.QLabel(self.centralwidget)
        self.pageIndicator.setAlignment(QtCore.Qt.AlignCenter)
        self.pageIndicator.setObjectName("pageIndicator")
        self.verticalLayout_4.addWidget(self.pageIndicator)
        self.pageProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pageProgressBar.setProperty("value", 24)
        self.pageProgressBar.setObjectName("pageProgressBar")
        self.verticalLayout_4.addWidget(self.pageProgressBar)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLow = QtWidgets.QAction(MainWindow)
        self.actionLow.setCheckable(True)
        self.actionLow.setObjectName("actionLow")
        self.actionMedium = QtWidgets.QAction(MainWindow)
        self.actionMedium.setCheckable(True)
        self.actionMedium.setChecked(True)
        self.actionMedium.setObjectName("actionMedium")
        self.actionHigh = QtWidgets.QAction(MainWindow)
        self.actionHigh.setCheckable(True)
        self.actionHigh.setObjectName("actionHigh")
        self.actionDistinguishByColor = QtWidgets.QAction(MainWindow)
        self.actionDistinguishByColor.setCheckable(True)
        self.actionDistinguishByColor.setObjectName("actionDistinguishByColor")
        self.actionStart_Analyze = QtWidgets.QAction(MainWindow)
        self.actionStart_Analyze.setObjectName("actionStart_Analyze")
        self.actionRest = QtWidgets.QAction(MainWindow)
        self.actionRest.setObjectName("actionRest")
        self.actionVerbose = QtWidgets.QAction(MainWindow)
        self.actionVerbose.setCheckable(True)
        self.actionVerbose.setObjectName("actionVerbose")
        self.menu.addAction(self.actionImport)
        self.menu.addAction(self.actionExport)
        self.menu.addSeparator()
        self.menu.addAction(self.actionQuit)
        self.menu_2.addAction(self.actionManual)
        self.menu_2.addAction(self.actionAbout)
        self.menu_3.addAction(self.actionVerbose)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CapSaint"))
        self.groupBox.setTitle(_translate("MainWindow", "Preview"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preferences"))
        self.label.setText(_translate("MainWindow", "Zoom Ratio:"))
        self.checkBox.setText(_translate("MainWindow", "Use Color to Distinguish"))
        self.label_2.setText(_translate("MainWindow", "Sensitivity:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Low"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.comboBox.setItemText(2, _translate("MainWindow", "High"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Extremely High"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Actions"))
        self.pushButton.setText(_translate("MainWindow", "Analyze This"))
        self.pushButton_3.setText(_translate("MainWindow", "Analyze All"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset This"))
        self.pushButton_4.setText(_translate("MainWindow", "Reset All"))
        self.pushButton_5.setText(_translate("MainWindow", "⬅️"))
        self.pageIndicator.setText(_translate("MainWindow", "10 of 43"))
        self.pushButton_6.setText(_translate("MainWindow", "➡️"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menu_2.setTitle(_translate("MainWindow", "Info"))
        self.menu_3.setTitle(_translate("MainWindow", "Advanced"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.actionImport.setText(_translate("MainWindow", "Import Images..."))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export Current..."))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLow.setText(_translate("MainWindow", "Low"))
        self.actionMedium.setText(_translate("MainWindow", "Medium"))
        self.actionHigh.setText(_translate("MainWindow", "High"))
        self.actionDistinguishByColor.setText(_translate("MainWindow", "Use Color to Distinguish"))
        self.actionStart_Analyze.setText(_translate("MainWindow", "Start Analyze"))
        self.actionRest.setText(_translate("MainWindow", "Rest"))
        self.actionVerbose.setText(_translate("MainWindow", "Verbose Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
