# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CapSaint/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 498)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 313))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.graphicsView = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setText("")
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_5.addWidget(self.graphicsView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.zoomIndicator = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.zoomIndicator.setDecimals(1)
        self.zoomIndicator.setMinimum(0.1)
        self.zoomIndicator.setMaximum(10.0)
        self.zoomIndicator.setSingleStep(0.1)
        self.zoomIndicator.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.zoomIndicator.setProperty("value", 1.0)
        self.zoomIndicator.setObjectName("zoomIndicator")
        self.horizontalLayout_2.addWidget(self.zoomIndicator)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.colorDistCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.colorDistCheckBox.setObjectName("colorDistCheckBox")
        self.verticalLayout.addWidget(self.colorDistCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.sensitivitySelector = QtWidgets.QComboBox(self.groupBox_2)
        self.sensitivitySelector.setObjectName("sensitivitySelector")
        self.sensitivitySelector.addItem("")
        self.sensitivitySelector.addItem("")
        self.sensitivitySelector.addItem("")
        self.sensitivitySelector.addItem("")
        self.horizontalLayout_3.addWidget(self.sensitivitySelector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.analyzeThisButton = QtWidgets.QPushButton(self.groupBox_3)
        self.analyzeThisButton.setDefault(True)
        self.analyzeThisButton.setObjectName("analyzeThisButton")
        self.gridLayout.addWidget(self.analyzeThisButton, 0, 0, 1, 2)
        self.analyzeAllButton = QtWidgets.QPushButton(self.groupBox_3)
        self.analyzeAllButton.setDefault(False)
        self.analyzeAllButton.setObjectName("analyzeAllButton")
        self.gridLayout.addWidget(self.analyzeAllButton, 0, 2, 1, 1)
        self.resetThisButton = QtWidgets.QPushButton(self.groupBox_3)
        self.resetThisButton.setObjectName("resetThisButton")
        self.gridLayout.addWidget(self.resetThisButton, 1, 0, 1, 1)
        self.resetAllButton = QtWidgets.QPushButton(self.groupBox_3)
        self.resetAllButton.setObjectName("resetAllButton")
        self.gridLayout.addWidget(self.resetAllButton, 1, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_9.addWidget(self.previousButton)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pageIndicatorLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageIndicatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pageIndicatorLabel.setObjectName("pageIndicatorLabel")
        self.verticalLayout_4.addWidget(self.pageIndicatorLabel)
        self.pageProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pageProgressBar.setMinimum(1)
        self.pageProgressBar.setProperty("value", 24)
        self.pageProgressBar.setObjectName("pageProgressBar")
        self.verticalLayout_4.addWidget(self.pageProgressBar)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_9.addWidget(self.nextButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 22))
        self.menubar.setObjectName("menubar")
        self.FileMenu = QtWidgets.QMenu(self.menubar)
        self.FileMenu.setObjectName("FileMenu")
        self.InfoMenu = QtWidgets.QMenu(self.menubar)
        self.InfoMenu.setObjectName("InfoMenu")
        self.AdvancedMenu = QtWidgets.QMenu(self.menubar)
        self.AdvancedMenu.setObjectName("AdvancedMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLow = QtWidgets.QAction(MainWindow)
        self.actionLow.setCheckable(True)
        self.actionLow.setObjectName("actionLow")
        self.actionMedium = QtWidgets.QAction(MainWindow)
        self.actionMedium.setCheckable(True)
        self.actionMedium.setChecked(True)
        self.actionMedium.setObjectName("actionMedium")
        self.actionHigh = QtWidgets.QAction(MainWindow)
        self.actionHigh.setCheckable(True)
        self.actionHigh.setObjectName("actionHigh")
        self.actionDistinguishByColor = QtWidgets.QAction(MainWindow)
        self.actionDistinguishByColor.setCheckable(True)
        self.actionDistinguishByColor.setObjectName("actionDistinguishByColor")
        self.actionStart_Analyze = QtWidgets.QAction(MainWindow)
        self.actionStart_Analyze.setObjectName("actionStart_Analyze")
        self.actionRest = QtWidgets.QAction(MainWindow)
        self.actionRest.setObjectName("actionRest")
        self.actionVerbose = QtWidgets.QAction(MainWindow)
        self.actionVerbose.setCheckable(True)
        self.actionVerbose.setObjectName("actionVerbose")
        self.FileMenu.addAction(self.actionImport)
        self.FileMenu.addAction(self.actionExport)
        self.FileMenu.addAction(self.actionQuit)
        self.InfoMenu.addAction(self.actionManual)
        self.InfoMenu.addAction(self.actionAbout)
        self.AdvancedMenu.addAction(self.actionVerbose)
        self.menubar.addAction(self.FileMenu.menuAction())
        self.menubar.addAction(self.AdvancedMenu.menuAction())
        self.menubar.addAction(self.InfoMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CapSaint"))
        self.groupBox.setTitle(_translate("MainWindow", "Preview"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preferences"))
        self.label.setText(_translate("MainWindow", "Zoom Ratio:"))
        self.colorDistCheckBox.setText(_translate("MainWindow", "Use Color to Distinguish"))
        self.label_2.setText(_translate("MainWindow", "Sensitivity:"))
        self.sensitivitySelector.setItemText(0, _translate("MainWindow", "Low"))
        self.sensitivitySelector.setItemText(1, _translate("MainWindow", "Medium"))
        self.sensitivitySelector.setItemText(2, _translate("MainWindow", "High"))
        self.sensitivitySelector.setItemText(3, _translate("MainWindow", "Extremely High"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Actions"))
        self.analyzeThisButton.setText(_translate("MainWindow", "Analyze This"))
        self.analyzeThisButton.setShortcut(_translate("MainWindow", "Return"))
        self.analyzeAllButton.setText(_translate("MainWindow", "Analyze All"))
        self.resetThisButton.setText(_translate("MainWindow", "Remove This"))
        self.resetAllButton.setText(_translate("MainWindow", "Remove All"))
        self.previousButton.setText(_translate("MainWindow", "⬅️"))
        self.previousButton.setShortcut(_translate("MainWindow", "Left"))
        self.pageIndicatorLabel.setText(_translate("MainWindow", "10 of 43"))
        self.nextButton.setText(_translate("MainWindow", "➡️"))
        self.nextButton.setShortcut(_translate("MainWindow", "Right"))
        self.FileMenu.setTitle(_translate("MainWindow", "File"))
        self.InfoMenu.setTitle(_translate("MainWindow", "Info"))
        self.AdvancedMenu.setTitle(_translate("MainWindow", "Advanced"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.actionImport.setText(_translate("MainWindow", "Import Images..."))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExport.setText(_translate("MainWindow", "Export Current..."))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionLow.setText(_translate("MainWindow", "Low"))
        self.actionMedium.setText(_translate("MainWindow", "Medium"))
        self.actionHigh.setText(_translate("MainWindow", "High"))
        self.actionDistinguishByColor.setText(_translate("MainWindow", "Use Color to Distinguish"))
        self.actionStart_Analyze.setText(_translate("MainWindow", "Start Analyze"))
        self.actionRest.setText(_translate("MainWindow", "Rest"))
        self.actionVerbose.setText(_translate("MainWindow", "Verbose Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
